/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void onDrawButton(GButton source, GEvent event) { //_CODE_:drawButton:448334:
  println("drawButton - GButton >> GEvent." + event + " @ " + millis());
  draw = true;
  rake = false;
  smooth = false;
} //_CODE_:drawButton:448334:

public void onRakeButton(GButton source, GEvent event) { //_CODE_:rakeButton:603103:
  println("rakeButton - GButton >> GEvent." + event + " @ " + millis());
  draw = false;
  rake = true;
  smooth = false;
} //_CODE_:rakeButton:603103:

public void onSmoothButton(GButton source, GEvent event) { //_CODE_:button1:419792:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  draw = false;
  rake = false;
  smooth = true;
} //_CODE_:button1:419792:

public void onResetButton(GButton source, GEvent event) { //_CODE_:button2:381538:
  setup();
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:381538:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  title = new GLabel(this, 246, 6, 80, 20);
  title.setTextAlign(GAlign.CENTER, GAlign.TOP);
  title.setText("zen garden");
  title.setTextBold();
  title.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  title.setOpaque(false);
  name = new GLabel(this, 234, 20, 100, 20);
  name.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  name.setText("by maddie mcroy");
  name.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  name.setOpaque(false);
  drawButton = new GButton(this, 81, 6, 45, 20);
  drawButton.setText("draw");
  drawButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  drawButton.addEventHandler(this, "onDrawButton");
  rakeButton = new GButton(this, 36, 6, 40, 22);
  rakeButton.setText("rake");
  rakeButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  rakeButton.addEventHandler(this, "onRakeButton");
  tools = new GLabel(this, 63, 27, 80, 20);
  tools.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  tools.setText("tools");
  tools.setTextItalic();
  tools.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  tools.setOpaque(false);
  button1 = new GButton(this, 131, 6, 50, 20);
  button1.setText("smooth");
  button1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button1.addEventHandler(this, "onSmoothButton");
  button2 = new GButton(this, 462, 5, 60, 20);
  button2.setText("reset");
  button2.setLocalColorScheme(GCScheme.RED_SCHEME);
  button2.addEventHandler(this, "onResetButton");
}

// Variable declarations 
// autogenerated do not edit
GLabel title; 
GLabel name; 
GButton drawButton; 
GButton rakeButton; 
GLabel tools; 
GButton button1; 
GButton button2; 